### ISSUE TITLE
erase on iterators

### ISSUE THREAD

**Issue by mgaunard** [tinloaf/ygg#4]
Trees should provide erase on iterators, returning the next iterator, for consistency with other containers.

The alternative is to use remove, but that's not compatible with algorithms.

**Comment by mgaunard** [comment]
Might also consider add erase_and_dispose in boost intrusive style.

**Comment by tinloaf** [comment]
You are right. I added erasing by iterator in https://github.com/tinloaf/ygg/commit/e073e6358ffe44416dcf776f3b9f4459f828f60f

I'm hesitant to also allow erasing by `const_iterator` - in an intrusive tree, erasure changes the underlying node, thus I would have to cast away constness there. Does this solve your problem?

**Comment by mgaunard** [comment]
erase should return the iterator to the next element

**Comment by tinloaf** [comment]
You are right - Ygg deviates from STL in this regard. Returning an iterator to the next element introduces a (small, but still…) performance penalty. Thus I'm reluctant to add that as a default.

I have added a `TreeFlag` named `STL_ERASE` which will make the `erase()` methods adhere to STL standards - returning an iterator to the next element, etc. Does that help you?

**Comment by tinloaf** [comment]
I'll assume that the `STL_ERASE` option solved your problem. If you still experience problems, feel free to reopen this resp. create a new issue. Thanks for reporting!
