### ISSUE TITLE
Is the method query() of intervalTree thread safe?

### ISSUE THREAD

**Issue by tigeroses** [tinloaf/ygg#7]
Thanks for developing this repo, and it helps me a lot!
I'd like to create an intervalTree, and use query() method through multi-threading, can this be done?

**Comment by tinloaf** [comment]
First things first: Just as the STL, I've developed Ygg without thread safety in mind. In other words: If you use any data structures in this repo in multiple threads, you must do the locking yourself.

That being said - as long as you *only* call `query()` from multiple threads (with no concurrent modifications), you *should* be safe. I just thought about this for a second and could not come up with anything that could go wrong, but that's far from a "thread safety guarantee". ;-) Hope that helps?

**Comment by tigeroses** [comment]
Thanks for your reply, I known what you mean, and I do some test, the result of multi-thread is same as single-thread.
